name: gtk_theme_fl
description: Gets the current linux gtk theme.
version: 0.0.1
homepage: https://github.com/gtk-flutter/gtk_theme_fl
author: Simrat Grewal (simrat39)

environment:
  sdk: ">=2.15.0-150.0.dev <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: GtkThemeFlPlugin
